//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_BackendAssessment.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int Email_Id { get; set; }
        public string EmailAddressTo { get; set; }
        public string Subject { get; set; }
        public Nullable<int> FolderId { get; set; }
        public Nullable<System.DateTime> CapturedDate { get; set; }
        public string EmailAddressFrom { get; set; }
        public string Url { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ErrorMsg { get; set; }
        public string Message { get; set; }
    }
}
