//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_BackendAssessment.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLabel
    {
        public int EmailLabel_Id { get; set; }
        public Nullable<int> Email_Id { get; set; }
        public Nullable<int> Label_Id { get; set; }
    }
}
