//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_BackendAssessment.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Label
    {
        public int Label_Id { get; set; }
        public string LabelName { get; set; }
        public Nullable<System.DateTime> CapturedDate { get; set; }
    }
}
